### ISSUE TITLE
Favicon not found

### ISSUE THREAD

**Issue by jayrenn** [MicrosoftEdge/JSBrowser#12]
Navigating to the [blog post](http://blogs.windows.com/msedgedev/2015/08/27/creating-your-own-browser-with-html-and-javascript/) in the JSBrowser, no favicon appears to be found.

Looking at the source code of the page, there is a favicon specified in the markup.
```html
<link rel="shortcut icon" href="http://blogs.windows.com/msedgedev/wp-content/themes/windows-blogs/images/favicon.ico" />
```
![favicon](http://blogs.windows.com/msedgedev/wp-content/themes/windows-blogs/images/favicon.ico)

Looking at the root of the subdomain, i.e. `http://blogs.windows.com/favicon.ico`, the URL does resolve, but no image appears.

Thus, the reason for this bug is the order of the favicon logic. Currently, we check for a favicon at the root first, then check the markup. We need to reverse this order, especially since the favicon's specified in the markup will be more reliable as a whole.

**Comment by jdalton** [comment]
:rocket:
