### ISSUE TITLE
Open sourcing Edge and EdgeHTML

### ISSUE THREAD

**Issue by trusktr** [MicrosoftEdge/JSBrowser#29]
You guys should open source your browser, like how Firefox, Chromium, and Webkit are. I bet this would bring about contribution from the community and help the web make faster progress.

**Comment by jdalton** [comment]
Hi @trusktr!

We :heart: open source!

In fact Chakra, the JavaScript engine powering Edge and UWP apps, [is being open sourced this month](https://blogs.windows.com/msedgedev/2015/12/05/open-source-chakra-core/). As time goes on I expect more projects and components to be developed in the open. 

<a href="https://twitter.com/jdalton/status/673190829024907265"><img src="http://f.cl.ly/items/250N2M3x400p0737292T/ms.gif" height=60% width=60%></a>

**Comment by trusktr** [comment]
Wow, that's really great news!!
