### ISSUE TITLE
Cannot build project on Linux using mono-xbuild

### ISSUE THREAD

**Issue by iegik** [MicrosoftEdge/JSBrowser#41]
xbuild: could not import "$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\$(WMSJSProjectDirectory)\Microsoft.VisualStudio.$(WMSJSProject).Default.props"

**Comment by jdalton** [comment]
mono-xbuild support is outside the scope of this project.
