### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by MPelaezE** [MicrosoftEdge/JSBrowser#42]
Hello team!

I want to use this approach of browser as custom browser for a client but their sites run via certificate based auth, we must implement that certifcation dialog like IE or Edges does, but dunno how can archive that and dunno the state of this project if it is viable to make something out of a demo...

Is there a plan to improve this project?
some kind of documentation to improve the "back-end" part by ourselves?

Thanks for your time!

**Comment by jdc20181** [comment]
It really depends, I highly doubt this project will kick off. It was made then abandoned pretty well it seems. 

I do not really know how to answer your question but I found something that is in JS but is kinda old, but still could work.  Find that [here](https://github.com/tgies/client-certificate-auth)

It requires Node.js to work. 

As far as improving this project, you could locate and fix misc bugs (and add them in a PR it would be appreciated 👍  )

**Comment by jdalton** [comment]
From the readme:
> This project is a tutorial demonstrating the capabilities of the web platform on Windows 10. 

Nothing more, nothing less.
