### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by USERUSERU** [MicrosoftEdge/JSBrowser#45]
Could you change code of this program, because number of color is not good for christians. Lets change this number to 777. 
Now, I will show fragments, where is this code is use
}
#urlInput:focus {
    border-color: #0078D7;
    color: #666;

.effect-moveleft .outer-nav a {
    color: #666;
    padding: 15px;
    margin: 0;
    cursor: pointer;

#favMenu .url {
    font-size: 12px;
    color: #666;

**Comment by jdalton** [comment]
Hi @USERUSERU!

In this case `#777` represents a different color (see [here](http://www.color-hex.com/color/666666) and [here](http://www.color-hex.com/color/777777)).

<table>
<tr>
<td>
<img src="https://cloud.githubusercontent.com/assets/4303/21957437/d8a54ffc-da4a-11e6-8350-94acd8a5b339.png">
</td>
<td>
<img src="https://cloud.githubusercontent.com/assets/4303/21957439/dacb6578-da4a-11e6-86cc-30ee4e505a90.png">
</td>
</tr>
</table>

As you can see by the table above there's plenty more to the color besides its hex representation. For more on the complexities of color representation see [this post](https://medium.com/@jennschiffer/welcome-to-the-church-of-color-and-code-f2828fde2ecd#.d02aesggg).

**Comment by USERUSERU** [comment]
But it is no many deiference from 6...6 and 677 (http://www.color-hex.com/color/667777). Please change it!!!
