### ISSUE TITLE
WebView not downloading Picture properly

### ISSUE THREAD

**Issue by Dinchy87** [MicrosoftEdge/JSBrowser#7]
Hi, recently I also wrote on the Windows Blog regarding this issue but now I have found you on GitHub. This is my issue I have with Webview and other apps have it too:

I used WebControl on WP8.0 and now WebView on Windows 10 especially on Windows 10 Mobile and the results for my app say that WebControl renders the HTML string better then the current WebView. On WebView with Windows 10 SDK pictures get rendered wrong if used on a Windows 10 Mobile device from the first build till the last all of them have this issue because of WebView.

This is something that the team must have a look into. My app has already a lot of Windows 10 Mobile users that see this bug and the app itself can not change this. The bug is that pictures are not downloaded properly if used via `NavigateToString()` to an HTML string. The string is properly written and the same string gives good results on WP8.1 with WebControl. I hope you look also in this because this is frustrating. I have attached one picture as example how the picture is not downloaded properly and there is no way for me to fix it. Calling a refresh, I mean `NavigateToString()` again solves this issue but why does it not work on the first try?!

I wanted to attach a screenshot of this how it happens but its not working. if you want to fix this issue you can contact me under *dino[dot]borogovac[at]outlook[dot]com* where I can send you the screenshots as prove that something is really wrong with WebView. Thanks in advance.

**Comment by seksenov** [comment]
Hello, do you have the string that you are trying to render? It doesn't have to be exact but if you have something that repros the issue I can take a look. Also what's the reasoning for navigating to a string rather than a HTML page through the Navigate method?

**Comment by jdalton** [comment]
\< Since this is a bit OT for JSBrowser I'm going to close the issue. However, don't let that discourage continued discussion. \>

**Comment by Dinchy87** [comment]
What do you think by closing?! is this not where we can report bugs for Edge and parts of it like the WebView?! if not where can i submit this bugs?!

**Comment by jdalton** [comment]
> What do you think by closing?! is this not where we can report bugs for Edge 

This is not really the place for that. This is a repo dedicated to the JS browser exercise referenced in the [MS Edge blog post](http://blogs.windows.com/msedgedev/2015/08/27/creating-your-own-browser-with-html-and-javascript/).

For future reference you can check out http://dev.modern.ie/community/support/ to file a bug or request a feature.

For this issue we'll take it off thread and continue in email.
