### ISSUE TITLE
Cannot build, missing NativeListener\NativeListener.winmd

### ISSUE THREAD

**Issue by DJDavid98** [MicrosoftEdge/JSBrowser#8]
After cloning the project and opening the solution file, clicking the Debug button (labelled "Local Machine") Gives me the following error:

|Severity|Code|Description|Project|File|Line|
|----------|-------|--------------|---------|-----|-----|
|Error|MSB3030|Could not copy the file "d:\Documents\Visual Studio 2015\Projects\JSBrowser\Release\NativeListener\NativeListener.winmd" because it was not found.|JSBrowser|C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets|3962

How could I make this work? Running Windows 10 build 10240 with all updates installed,

**Comment by jayrenn** [comment]
Hi @DJDavid98, try building the NativeListener project before deploying. Let me know if that resolves your issue!

**Comment by DJDavid98** [comment]
I can run the project if I use x86 instead of "Any CPU" after building the NativeListener, but I don't see an option to build it in x64.

**Comment by seksenov** [comment]
Hi @DJDavid98 is the x64 option missing from the Visual Studio drop down list? You won't be able to use Any CPU as the C++ component needs to be built for each specific architecture.

**Comment by DJDavid98** [comment]
I can't build it using the dropdown, if I double-click on it in the Solution Explorer it refuses to open up, and if I right click on it instead the only option I have is "Build" which builds it in x86

**Comment by jdalton** [comment]
@DJDavid98 Are you on Windows 10?

**Comment by jdalton** [comment]
Woops, you mentioned that. nm nm :D

**Comment by seksenov** [comment]
Are you using Visual Studio 2015 and a 64 bit version of the Windows 10 OS? Could you post some screenshots of what you are seeing of why you are unable to build from the dropdown. 

And just making sure you are talking about this drop down:
![image](https://cloud.githubusercontent.com/assets/7948683/9554794/642e7eba-4d7d-11e5-844b-261ee9b1a9ca.png)

**Comment by DJDavid98** [comment]
Never mind, I had "Any CPU" selected while I built the NativeListener, I just had to change it before building both items to make it work. Thank you for the assistance.
