### ISSUE TITLE
Please Expose DOM/API in UWP

### ISSUE THREAD

**Issue by Michael-DST** [MicrosoftEdge/JSBrowser#9]
This is a pretty cool project.  Good to see the extensibility of Edge.  There is a problem with your implementation, however.  UWP/.NET developers like coding in C#/VB.NET/F#. :)  So, it would be nice to either:

1) Expose Edge DOM in UWP: https://wpdev.uservoice.com/forums/110705-dev-platform/suggestions/9126583-webview-expose-dom-as-c-net-api
2) Enable UWP to transpile artifacts into web-standard compliant artifacts/executables: https://wpdev.uservoice.com/forums/110705-dev-platform/suggestions/7897380-expand-enable-universal-windows-platform-to-transp

The first is more applicable to this repo, but even then I realize this is not something this repo would solve exactly.  You need a chatroom/forum. :)

It would be great to start seeing more discussion (and awareness) around these issues.  There is a huge divide in the MSFT developer ecosystem between web and native developers, and it *incredibly* costly (on many levels) to MSFT and the developers that follow it.  Ultimately, this repo (or more accurately, its owners) will most definitely assist in getting this reconciled and protect MSFT investments/assets in this regard.

Thanks again for being innovative and producing this project, and for any consideration towards these issues!

**Comment by jdalton** [comment]
Thanks for the input. This project and tutorial is targeted more towards the JS/HTML/CSS crowd.

**Comment by Michael-DST** [comment]
That is sort of the problem @jdalton  ... the Native/UWP/.NET crowd can also be the JS/HTML/CSS crowd, too.  They are not mutually exclusive camps as the narrative you are perpetuating seems to suggest. This is a systemic (and costly) failure in MSFT culture and is one I pray is addressed sooner than later.  

In any case, thank you for your input.  The one thing that GitHub really lacks is a good forum/chat room, so this issue is very misplaced and indeed invalid from this perspective.

**Comment by jdalton** [comment]
> That is sort of the problem @jdalton ... the Native/UWP/.NET crowd can also be the JS/HTML/CSS crowd, too. 

I know I'm a JS dev and who makes web applications and the tutorial was targeted for similar folks.
Yes apps can be made with other languages but that's not the scope or focus of this exercise.

**Comment by Michael-DST** [comment]
> This project was targeted for similar folks.

Well I do appreciate the efforts, don't get me wrong, but if a web developer can develop an application that can reach 100% of the known marketplace via a modern browser, then why would they bother making an application that restricts them to a small % of that said marketplace?  Windows Store marketplace is dwarfed by both iOS and Droid stores, and even more so by the general web.  So, why would a web developer want to put their efforts into a paradigm that only caters to a sliver that can be accomplished through their traditional (established) means?  This is really the backwards thinking of UWP JS, IMO.  It's a really questionable (and confusing) strategy and something maybe you can help explain to me.  It seems as if UWP should be catering itself to JavaScript (as I have outlined above), not the other way around (as this project promotes).  I just don't see the motivation in a web developer saying "yes, I would like to decrease the capability of my application to be viewed by others by 90%...  sign me up!"

> Yes apps can be made with other languages but that's not the scope or focus of this exercise.
I agree, I am just working with what I have here.  See: need GitHub forum. :)

**Comment by jdalton** [comment]
> then why would they bother making an application that restricts them to a small % of that said marketplace

For me it's access to WinRT apis and app functionality. Hosted apps are really interesting to me since it's essentially a website that when loaded as a hosted web app can detect and access WinRT apis and extra functionality. That's super cool.

> I agree, I am just working with what I have here. See: need GitHub forum. :)

Thanks for the feedback.

**Comment by Michael-DST** [comment]
> That's super cool.

Yes, I hear that.  That is impressive and there is certain appeal to it.  But, again I struggle to find the (business) motivation for the open-web standards crowd to jump in here.  Don't get me wrong, MSFT should MOST DEF be into open web-standards and making the best of it (and they are doing a great job of that with Edge -- getting the warm and fuzzies there), but expecting web developers -- or ANY developer, for that matter -- to cater to a paradigm that is a % (no matter how big, actually -- as _any_ percentage is a regression and wasted effort) of what they can get by designing their web applications through existing means _simply does not make business sense_.  As has been with the case with WinRTJS since its inception, the only developers that will be interested in exploring this are the developers/teams/organizations that MSFT is paying to promote and build around it.  Hardly a viable model.

**Comment by jdalton** [comment]
> As has been with the case with WinRTJS 

Just checking, but by WinRT I mean https://en.wikipedia.org/wiki/Windows_Runtime.

> Hardly a viable model.

I donno about all that. I'm having fun with it. Are there forums where you normally discuss this stuff with other folks?

**Comment by Michael-DST** [comment]
Yes, that is the old UWP.  It had this incredible notion (no, not really) of accessing Windows application components through JavaScript.  And, as you can expect, no one uses it and was/is a terrible failure.  It's a comedy it still exists in UWP, and was/is a terrible idea and strategy for the same reason here -- if I am going to use my talents/resources to build a JavaScript-based application, why am I going to waste them on a restricted paradigm that reaches (at most) 10% of my target audience, when I can just deploy a website and reach 100% of them instead? :)

> I donno about all that. I'm having fun with it.

That's great... but tell that to MSFT shareholders, and see if "fun" meets the requirement for their %'s necessary for their retirement. ;)

> Are there forums where you normally discuss this stuff with other folks?

Nope, just GitHub mostly... that's why I say a forum here (or somewhere!) would be great.  I am also a huge MSFT blog hound and am pretty much subscribed to all the major ones out there from MSFT properties.

**Comment by jdalton** [comment]
> Nope, just GitHub mostly... that's why I say a forum here (or somewhere!) would be great.

This is most likely not the place. It's like talking corp policy to a Walmart greeter. I dig it and think you have an interesting take on things but really not sure dumping it all in a repo that's designed to support a JS/CSS/HTML exercise is the way to go about it.

**Comment by Michael-DST** [comment]
LOL!  Fair enough and *perfect* analogy.  Part of my ire is against Edge browser team, so anyone associated with them will get an earful.  Oh, I am also on UserVoice as well (as you can see above).  Lots of good conversation over there, too.

Again, I'm glad MSFT is focused on open standards and web... but there's this huge other side that is just being left in the cold.  It's a costly divide that is NOT mutually exclusive and we have to start building awareness towards mending it in any way we can, even if that means screaming in the face of Wal-Mart greeters (awesomely perfect analogy LOL). :)

In addition to my overzealousness, I also fault GitHub, as it is great in a lot of ways, but the one place it really fails us is conversation like this that gets mired in issues, when those should be used to directly impact product quality.  

Anyways, thanks for the conversation, @jdalton. :)

**Comment by Michael-DST** [comment]
FWIW, a quick note here @jdalton ... I took your (great) feedback and have created a series of blog posts (along with a UserVoice vote) to better articulate the problem space that MSFT is facing with their client application model strategies.  You can see this series here:
http://blog.developers.win/series/bridge-to-dotnet-ubiquity/

You can find the topics above in particular found in this entry here:
http://blog.developers.win/2015/10/the-backwards-bridge/

Thanks again for your dialogue, Walmart greeter (LOL... still cracks me up)!
